apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/duckdns/overlays/homelab
  - ../../../apps/forgejo/overlays/homelab
  - ../../../apps/orcamentos/overlays/homelab
  - ../../../apps/wireguard/overlays/homelab
