apiVersion: v1
kind: Secret
metadata:
    name: mempool-backend
    namespace: mempool
type: Opaque
stringData:
    core-rpc-password: ENC[AES256_GCM,data:CWrV1a7FLe0G,iv:xcmyDRXOCYnDPIfcBfszOTLxeEw4ZV9ggdg2RXsT4I8=,tag:XPMGbNqE8k8iG76NUK8Cew==,type:str]
    database-password: ENC[AES256_GCM,data:Ku6uUdbifKSr,iv:R+Guq1OuEvMKgYeT7iV+CVsx0LrBtxzHYG3qyffAOnY=,tag:fjz79t4tj50rM8J1rbj8hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNmJobmc2aldDOXY5dGpI
            VHZIVGgzWWxDUFVKdG8xVUQ5cUtUWTRzOVRvCnBaQzluZHBXSlg2c3hTbXI4Wjlk
            M0lRbnhVTlllOThwRTQydjhiNWZxdmcKLS0tIEpoQ2FKQkVMMFY3QzJkb1NLWXA4
            TUdtQlNuYzllTXpHSENhZTJkUzlPMlUK9NoiHkBoJ3p0SyzFA4ZiB6IkVsuY73zO
            3sF637BLr2uw7kl452oI6aGXUer8RKyxnnpxDogVZRdtVhBInbCOzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T23:15:08Z"
    mac: ENC[AES256_GCM,data:FWPle1nJQygqCS5Cg6bcDXzt9bscFGTKCecacwCbvUQ3VhYKAdap0X8y60DlpNjxOXOUbchRdQB5L8jgecUL22Fw4wki9PVOPDHxyBgK/jchKKuc4XtOEM9DEkoEj6XRf+8O/tO6a9dVUQdSR/c4G2bd3T2H6y3yEbuAoVz1jCA=,iv:T+TxB61m2MgM7rCsbhKrPxO1w0EhIwZpqp2cuFAuxSQ=,tag:kY5v23ObSyfyivgMouWsow==,type:str]
    version: 3.13.1
