apiVersion: v1
kind: Service
metadata:
  name: mempool-frontend
  namespace: mempool
spec:
  selector:
    app: mempool-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
