apiVersion: v1
kind: Secret
metadata:
  name: codex-secret
  namespace: codex
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  APP_ENV: ENC[AES256_GCM,data:hhE4pNA5XA==,iv:7gaP0tSdjD1t5kslUTMnX6oeu2NEElVey0SfllR1PQY=,tag:PitSC/k+iaFWTdqt+YDBfw==,type:str]
  BASE_URL: ENC[AES256_GCM,data:oHKwunT0c5xXPuh+dL5MhRvbG2N51/vWldcw,iv:mkJevvc7Axm4B3YTCHYiP4wpMIDWbG7qqo8bax2pdGA=,tag:u2cf2A5J0vfNMn0N6pPHwQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYUZ1NWFKUytVckdLdnQz
        dzNnNWdjK0RrbUVQRE1BekVlY1ZJeDJucm4wCjVSbEphWEFJalUvS2Q1U0Z0T3Bz
        dW5IclZqNHJRelNSclNITlMxMHdSb1EKLS0tIC9YQjdBMUliSFZ3ZHFoVlk4aTVN
        UVhmVnY1MU02S3BzOEZBeXE0c1hVdXcKaGtZc3xdVBnLAgAgLK1bj5037hXFxVk+
        XCLvwyiGy0iVOW11z+B0y8+oTN99N7146Xq0xOnyCrgvWLeMzL1eGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T00:14:40Z"
  mac: ENC[AES256_GCM,data:R7QTkxO0zwSPKWe5W3R18ei9+ZOBuaYvpfkNeQCifLHInkPMwxRCO1IFw3B81QMuGyNgQEsm0gr3qAuBByBP9rOYR5dyMGsjfEGyi5tXfGq8RLo9zR+ILc0kqN9sEL9/vhNwyxb/9Rv6tqyAIHTtgiKdJgv/Y+dnDEi5VHdQivY=,iv:cRCTVT4AGVZDrbRiwOrG1T6tIs6F43EQrAFnHzNqJ6w=,tag:g2YBVALjh9uwBLCUB3FkQQ==,type:str]
  version: 3.13.1
