apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres-cluster.yaml
  - postgres-secret.yaml
  - prisma-job.yaml
  - secret.yaml

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml


