apiVersion: v1
kind: Secret
metadata:
    name: app-db-user
    namespace: agente-ingles
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:UNPw3Xp4,iv:YztOSrUaGOXuOXda+O1q+4F1lfS/1UJ2MtAlBXJ6ndE=,tag:GxqQWv/IqfLxZmKW0LwX8w==,type:str]
    password: ENC[AES256_GCM,data:bRCLzwxt9esnEA==,iv:gCkv0BhhWdSaVKAIMqfYmAcuolfBKcZJ9zcr8Q0Ye08=,tag:NnbCMmKU5rE5SwkL6eTAqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZHl3WWc3ZHE3Nlo3MU9p
            cTFtWCtwd0F0V3Yya2xtY2FPR2o5enhoQ1dFCjRLOXU0MjMzOG0xZ3VHU01vYjZv
            bHg0YWZpb0tTM3padEtsaEF0emx2U2cKLS0tIHlWTERCc2FlN2V4TEt0OHltaXAy
            NnFHd1AraGRvN2tubGFodnZJR2FtcUkKAd1/Wd1URkEdAaKfY8ElCYKPXQAyBlUc
            yotIB2Ag8xM3YURToFlFKBTNtpsQGsSxNUBH7gzZPVj5TANyCS1Knw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:17:08Z"
    mac: ENC[AES256_GCM,data:oTdby78XtNubW0JRVjYej80AlzBYlszEBzyBx6Op7m3yQxjzqyIn+0eY/j3iaNXULubcK6TH1L7I9GnOnmEyg8Db7t/Eza5xpvW36PvzK+2eW/Rf9ZwH2WNPFSOYVbUKpP4h/ZJ8tdwzxGL3Z8R64hbPr+0lsnIEBzLdaCONg1k=,iv:ce8WeQ4/yUzA+z5FI3H5LtRz+AnRDKourRDw9h/qbQQ=,tag:x/CKJbCa1EoFUNBA7Ppqmg==,type:str]
    version: 3.13.1
