apiVersion: v1
kind: Secret
metadata:
    name: agente-ingles-app
    namespace: agente-ingles
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:LH4TnxP1Z8NmKtNTgFtZ8alQIE5vTaugGFiZZFkAEZhkTTM0Goqp5wQQfrq6He8bYUKconBHK/3+yWo=,iv:FMUPXzqbdaCvzWrhDuzS9EDY6KuRqAAh4/oBrHD7aoo=,tag:1jqPMwspxjbDcRGQOMxKYA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:samJ1y/N2wU+DwjHAQJ4bWJeUnsHj7fazA==,iv:EA73dl0IJjCye1FU48brpsQreW7CR16zdZd6BEZ+vEw=,tag:7LVy50+ZPFtxhD2VRT6Riw==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:jDbhUktWAqK0yxi+c6/ue4H0v2YMSS9TNXY6ulMV90cd,iv:cZuXE2OzvJFUVq40D/xVDi1EfpwpzBIRSNDV4KMBIMs=,tag:m4M3mlvsaLbvt7jFYcYGnQ==,type:str]
    OPENAI_API_KEY: ""
    OPENROUTER_API_KEY: ""
    ELEVENLABS_API_KEY: ""
    ELEVENLABS_VOICE_ID: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeUhhSlI0STkzclFlZVRX
            SUswaU9KZE9zTHl4ZUVYN2JCWEJvYnd4VFZNCisvVC80MXJZZHRNZDJOYTluVkhk
            bmh6VjRIUUR5RG14WHgwUkJwK2QzSEUKLS0tIDEwQ3BnR0VJbHIwQnpTUlpvTUVP
            Zkc2Ly83bW9keDEzSmhRdzZJYXk4M3cK/74Ko1HohnKGxXIbSB2XzBk4XRssC9bl
            WP1+fZTqhIgACffO0y78T5DS9ZdzclFvGmnbWhnMbvgTi+0ip+VzPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:17:08Z"
    mac: ENC[AES256_GCM,data:8xazOER2Sju7R5uosaFPWV8X1ojftyrUJuVaitW3cowFTGqGX0q6RyDdAwTsC2jVnpRKGOwCHb1bg+eaj9RecxX3Ul4UKgLZbdNu6eRrXkuuKyySf3Q2LOIrPLI1TetKMYIcY4dTBMzazeQXQ3b2KYF6GKEbUDnC3tMJDSzUZEs=,iv:r7+1z39SalvPk5aOC7xFOP2NhK1R1xVUDYONEjMtPZo=,tag:xYa7fcy62URlPN/2sB6MJA==,type:str]
    version: 3.13.1
