apiVersion: v1
kind: Service
metadata:
  name: agente-ingles
  namespace: agente-ingles
spec:
  selector:
    app: agente-ingles
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP

