apiVersion: v1
kind: Pod
metadata:
  name: toolbox-maintenance-rasp
  namespace: maintenance
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-rasp
  containers:
    - name: toolbox
      image: 192.168.1.191:3000/henrique/toolbox:arm64
      imagePullPolicy: Always
