apiVersion: v1
kind: Secret
metadata:
  name: mempool-mysql
  namespace: mempool
type: Opaque
stringData:
  mysql-root-password: ENC[AES256_GCM,data:sorkzWPYeMoX,iv:OrDwRyVruDwr9+RlarWkNZX92lZKnkiRahhxgXqsYPg=,tag:FFAVETCGqSf6hyBUG+G0Cw==,type:str]
  mysql-database: ENC[AES256_GCM,data:ll2j98mtxA==,iv:L5xDAdkqcLZKmuTWB2d5ksiyjr4kn3MMgR9jzcxgh+o=,tag:pl0n3OFrM+ySJDsACzMDbw==,type:str]
  mysql-user: ENC[AES256_GCM,data:lbDs6O6vDb4=,iv:+bD8awxrUhTzpP01IAZ1ty/GcSIu6ONYx94JflvwM2A=,tag:iaCEkRpPSSYTmG0Bui19CA==,type:str]
  mysql-password: ENC[AES256_GCM,data:s5rcoYXcW01a,iv:81hJ0u9Pcs8HpQizLSJiCwIO6E8PEKz73jE3gxWOcDQ=,tag:OU03PWY9Bota5+03lFWstw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOFBGeTJ3UEFoZ0puNmlT
        R3k2Wlh3eUNDR0dhRU90UDRzSmQ2Z2s3cFNJCnljL01iUkN3SFBXZUVqUFVnZi9W
        Ukx4YzlWS2xpckljRDFteHNxSWJEakkKLS0tIEo0M0tXK3dad0VaNUx0bHNKbEVC
        ako4ck5Wb2VVVko5YjNrL2tqNmI1THMKvJ4KWnwHseMOtd3ux5f8F4gjriC851ml
        KroYkxaCRLkObQ94ztnpXi6UeplaW2Mj3jFp84dnMvQvLmttOdU6Hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T22:45:22Z"
  mac: ENC[AES256_GCM,data:qilXBeov8z15eZeM2thVThrvNxVXtSzldGych0ar2uHqinK0LJIqPQgla552USjxG9T1l7JtjkPevZClX/nxGp7fb6hwr37+21GpH6rGXpY/pTfzYR1AvEoHLlIYj1/Z2CV01hKdZd0N8MGSAQ0LnUOlv2UcncquWqZeE3XXN/w=,iv:FtRMFp9ZT2GVK6VqJwTB09cAeTrzJgTwpJQG3wr8c3w=,tag:prcFwPFYSWHBAumWKng5yA==,type:str]
  version: 3.13.1
