apiVersion: v1
kind: Service
metadata:
  name: mempool-mysql
  namespace: mempool
spec:
  selector:
    app: mempool-mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
