apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudnativepg-lab-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cloudnativepg-local
  local:
    path: /var/mnt/ssd/cloudnative
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-rasp
