apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudnativepg-lab-pvc
  namespace: cloudnativepg-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: cloudnativepg-local
  volumeName: cloudnativepg-lab-pv
