apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: cloudnativepg-lab
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:71p0,iv:3Qk0V8SXat5FBJOWIljVrqdNoRNc1DfesZaHGx5Uihk=,tag:j2qjexWWOAHV+l07v/zLyQ==,type:str]
    password: ENC[AES256_GCM,data:fW4PajkDk7ut,iv:43sbStt867vj14yWxA0MUUwEQ/Ijvr+jMM9JWR6PqV4=,tag:2JS3UGH6BBQwLNp/KBZ4sA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybERDZWxQYmUrTUxWenhC
            YnZBb1pOWjZpcjNlSTgrWDJmdVpIaFhVcERBCkVrUHFLSFZYVjJ0cXYrbzNONjZy
            cXc4clcyQjhJa1lRYlFrRmI4MzFERDgKLS0tIHNnZHFVS2ErMXNHeXVlRGR6aUx2
            NlEwcjQ3a1lLcTBrV1FLOVcwSnVXUmsKio9g7XrDXNjWT6TmeSWBSLYiJ2Vu9BWo
            ShJL1erMTYa/06o0+xQkfHnzq/p2/eWb5j9BeosAN/4hk8ezkxzUJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:17:08Z"
    mac: ENC[AES256_GCM,data:Xfrxi0sNCnnUxgqoPDDbR6GSfwEIAYJp/KHCq1LFrJx7K/Oi+XeTwEyXA9Q5o13v2WDlp/1kfN+WirCs0VRg6hqY7VKRK2Jkol25l4Evkmt0hbdXlna3f5bwTm/2GTDApLrB9Kii4hGUWZnBujtYwL1fOq8Isl1bZlYunnAFp5A=,iv:LHSfmh4t85mQnXURw4wpdPszfBi1NQIOqGLUfxKRGb4=,tag:W4PE113JGKEBgPcJjsth3w==,type:str]
    version: 3.13.1
