apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
  namespace: grafana
type: Opaque
stringData:
  GF_DATABASE_USER: ENC[AES256_GCM,data:fS373UWtMw==,iv:m8Ty5962z5tJ/8mOGGS7rRpWknqVrBd68Ul5rjXxNsk=,tag:kJ6rYhOCZTCkG2EMSkTLKg==,type:str]
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:tGMs3RW+bmZVXkFwdw==,iv:N5uPDIv40Xb4urvsKMDEfbxQUltlEpAAKMxJxyFSXd8=,tag:f+S/WSuQR7Kd+IUSRPN5+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVzFKQXJOUlFKUmNBQ1d2
        KzdHNSt6dFYxOXlFejVxaXhwb0ZVZWR1QVhNCkN5YUNTWGsvNjJGajdpOElDQkhJ
        UGg1RmxtNVF1R2FZcW1YVndBckdWWlEKLS0tIFU4T3VDK09PU1h3bnJPMDFaUWxO
        S3FuR1hIVUNpeVVYMWs0b3RzcW1hZHcKJQtgjyPJhsYffPhlqT3v7jI+BrVBaxcM
        REWrqoZD/yB2F8pVwN4wjrOEPbNiMg8fFdHfW8oSAtr1Q7zJWjV1Yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T00:17:08Z"
  mac: ENC[AES256_GCM,data:mekzIZ0xiwV4pzUFzPIXznI019NT1N9cGoSqmJut9TH/K7ZJkPMPt3IFUa2tfLTIjeMyldbX0vHCFfchPgHGn+qGw3A4+AavWbYs7E3aZ+1XCkxUt5mlpUN5acJ+b/XuXsjzmectxvRAHZlHwaTIADHmTnhDmYt8D/Tntx6ygs4=,iv:4dgCvMYP/3pcFZwyLUG8Sudec0o19v4JuTMhjYlNNo4=,tag:LWfHq4jmPwj/aud1im0r8w==,type:str]
  version: 3.13.1
