apiVersion: batch/v1
kind: CronJob
metadata:
  name: pc-on
  namespace: pc-on
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pc-on
              image: alpine:3.20
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
              args:
                - stty -F /dev/ttyACM0 9600 && echo POWER > /dev/ttyACM0
