apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-proposta-taube.yaml
  - deployment-proposta-api.yaml
  - service-proposta-taube.yaml
  - service-proposta-api.yaml
  - namespace.yaml
