apiVersion: v1
kind: Service
metadata:
  name: orcamentos-api
  namespace: orcamentos
spec:
  selector:
    app: orcamentos-api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
