apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml

patches:
  - path: patch-deployment-proposta-taube.yaml
  - path: patch-deployment-proposta-api.yaml
  - path: patch-service-proposta-taube.yaml
  - path: patch-service-proposta-api.yaml
