apiVersion: v1
kind: Service
metadata:
  name: proposta-api
  namespace: site-orcamentos
spec:
  type: ClusterIP
  selector:
    app: proposta-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
