apiVersion: v1
kind: Secret
metadata:
  name: site-orcamentos
  namespace: site-orcamentos
type: Opaque
stringData:
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:azd4X4ULZ1NISNB4sfqACUYurPsYlkc/bub5N1SQieMKv4V2WRGEXALU2B3HHiSQ9HAqJ1Wjjg7iBENeDdUlNV7wdnyOm4xTbUxVWXpyBtRi+fFjENeviKYRgFEdBjTR/qfLW4Noh/mp/eQJ,iv:5MTlxWIBfIvrMEg6bZOAAUF3DLekHM/s2AcBrWrLdLE=,tag:ckkqTrlwL45ddbAPHyBO3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbXFyL1MzQW1qTjY4L3V3
        ZTU2MjZBSUMyOEJIRHJsZVBFRlhIdzVVY2dvCkx4U1QrY1ArZTNyVUY5TU9NSEpK
        eTlPZXcrUjNPMzBLSFNRT2ZoMXByY0kKLS0tIDcrbm41ZnFrUERqMUM4c01ia2FI
        NkZvdzlFNWVzdnBWOTR3cjk1RlFQWEEKnszWDRZTpKZDByNecNh2gWyIwN7SfJCP
        DwqxxSmlHL4CbJMbZVD1cxNjfI03rY4qpQ+BDSUGzwIpvyRMxkNviw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-10T16:38:17Z"
  mac: ENC[AES256_GCM,data:K4M5R/W4ebdSCC4bwUIsmB76nHWRwiYn2m1U/X41zk8o2zPfIGwZeXsmeCoYM/VbNOM++jGd4t403yZFR/eJ94rqIwxoQ8Dre93I2wu0xOHFeMwi6RO8HWZnZAjYDguEkQfwyZkXED16L7roUTPhwgmgeHA09VTtWd5Xsxj/1w4=,iv:OZSTWnMwAbgTTBw44mcGp3ZnsqaUxIraCENZTMv2+U0=,tag:7RaUv4OXECxIHZXWUhtDTw==,type:str]
  version: 3.13.1
