apiVersion: v1
kind: Secret
metadata:
  name: site-orcamentos
  namespace: site-orcamentos
type: Opaque
stringData:
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:0HxvAUAO6V/+dZ+GUBPX+479RfdTLn/PZXWy59XSdc2NBS3QUTKtfrfdsTE0mzRBcWQ5GsbzBkbsa4htXaCojIcOf5ptTBQO2KyeoeFywZihTEMe1bcUgAmX/gZfrGoZa+7x+lszKqNWMGNo,iv:2f69oN9xnMKmWZvcYomTSDwe7N9Iyu6+r0wiDMcaqps=,tag:BJ9HXSveSTFf9BzIslI3ag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcnoxejlFMnRsVW1Zb1RC
        K3VPNVZrNGluQXBQRVFTdElpa3lCUThHN1d3CkdLYmtrVXorbGlYN25uOFRvV1Fy
        dVcrSTJWNThxcDRRS2JNMXpvcDlQTWMKLS0tIDJMMXBPYXc3SzVZQUZ3L3BuakVF
        REhtK1V6STFXTEZIOENtTWFtMzZTVjAK9zZ3DiB04dCf1AzUyLMtlfho+kpU5Snd
        fFArNzaLHWOOMzEKXQTaA45Gnth9sIE7U6dwGl6b9ClVPfcUh9U07A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T01:01:40Z"
  mac: ENC[AES256_GCM,data:Rh3EUQpV3bvNcbeZj6DyArqLregiNtrghtJampu1/Vt6sZM/d4BCpPtiCzPtyGceE2cc+iu9NR5rAvqhp+HRZqmejxPwl2+b84xScbp9K6GBR55dcIkyPQpf63hH7GBZjyZZwiCnHvbRDqXPomeoPMzmaUBJArYNQFh8r4/njMU=,iv:Kh5cwB/0M3yx3R19x4r3wsTRjOhx6MgfTT0rtez86+k=,tag:Inq8yaVuwfVcSFxvX3UFFA==,type:str]
  version: 3.13.1
