apiVersion: v1
kind: Secret
metadata:
    name: orcamentos-openai
    namespace: orcamentos
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:5iNAqLO9nMulmg==,iv:Asj4cMaKGIDqDpWG/dawRmS71GzkLROGGa4FiNfEH8g=,tag:DYhsSeoghiHxjOcCzJEPfA==,type:str]
    APP_USERNAME: ENC[AES256_GCM,data:A1zn9MFOTQ==,iv:dxixhmZ19mI3wZ+bcv/Kr20D3+ZkflskcdThr0uK4FE=,tag:y6KuCq3F8bUrE6Al38YMKg==,type:str]
    APP_PASSWORD: ENC[AES256_GCM,data:YgNfBeV99/yeXyI=,iv:XQAxv2cRaHXY0/JkIYinAC6pNaJuCP+b8UR8drnGIxg=,tag:lvtBcsIQ2lLogsDeLOqFcA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:UAOBggDmveZTTA==,iv:PVY+X6uA8MVvKJ58WjKXGYbE9217I8gpXwQzINa/Gvg=,tag:15lHjqSqKMjkj6g1KRLhrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbXFyL1MzQW1qTjY4L3V3
            ZTU2MjZBSUMyOEJIRHJsZVBFRlhIdzVVY2dvCkx4U1QrY1ArZTNyVUY5TU9NSEpK
            eTlPZXcrUjNPMzBLSFNRT2ZoMXByY0kKLS0tIDcrbm41ZnFrUERqMUM4c01ia2FI
            NkZvdzlFNWVzdnBWOTR3cjk1RlFQWEEKnszWDRZTpKZDByNecNh2gWyIwN7SfJCP
            DwqxxSmlHL4CbJMbZVD1cxNjfI03rY4qpQ+BDSUGzwIpvyRMxkNviw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:16:46Z"
    mac: ENC[AES256_GCM,data:dhuK1ByZ9VNICoMTyJ4f7rVbyONqT43t20U8+aFF2TW4OgelGWznlI7eeGvtFBGZgghkIvVXSxyjwuh0PrBiT67cXVUjaoVxeaQNXpH2EyKoYN4/KamVbf4ZdGlFT4Km4ShI1VvkIa0ml3xgPksYEQ26Pt0fEogtLoEW2w9XJYA=,iv:saidk/YulSyb4Pf7nGWY+8c1NRib+TOC7d/uJwAKdGk=,tag:ozdOnZFEi18FlAs8RnKQ5g==,type:str]
    version: 3.13.1
