apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: grafana-longhorn-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:o7jMO7Ljdw==,iv:07KBv0AbkIoAkjy1zL7wozFcEv1OL3njzCSsrUBsfZI=,tag:6Lzqv7N2R7c5ZFQHrRbLog==,type:str]
    password: ENC[AES256_GCM,data:IhrkBY38/Ps6fIqzTg==,iv:BMlNE/+B6ck5qeP/r3cmGrXJEl3PPQ6nppKqrRMAmDY=,tag:bS/P7a55EbZKX0J/syW3Gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OFhCVnd2TmxiZVNJNDNF
            SDk5SVYvYVUrUU1sSi83eDBpSVM3L1JUc2gwCktHVmVWNVlhRkVlV25odEk1L2pX
            V3dUV1lLWVRQbVptMHE5WUQ2SW5ZR28KLS0tIEpObnBHNGdUdU1LUW01NERueGh6
            SWNoVWVRTzVnclR1RUJIVzdEMmk3QVUKWzdefeCGoUg3N0oUvl14KUQhhmRwJSOI
            kvdP/Rdy2w5W1HX9vzJORYtFgxwURQ5DsHiRDEkABaZV70Vo4yOk3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:17:08Z"
    mac: ENC[AES256_GCM,data:gDyarA0vMPkMkl4q2OShlUiZeVucrrs6yT0ZcF4qr0OhUfCqKvv/HKBBaW+cJP7HIzZOujGMcAkV4PADoQ8AWdR+sfPCWsRjXvxBF9SfyI7yoTF+Q/+ADY0DMdefD4skaptHKfjMtkOuUztRIx5zzCVTq+fKa1CLyXM9TPQMUzo=,iv:+TNbtuJlfHAo/Bps7aCkxnVnZNqsRNrcfP2EZ2szmQE=,tag:igNl+2e78gcMMM+Cm1KjQQ==,type:str]
    version: 3.13.1
