apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
spec:
  template:
    spec:
      nodeSelector:
      kubernetes.io/hostname: worker-prox
      containers:
        - name: wireguard
          image: 192.168.1.191:3000/henrique/wireguard:multi
          imagePullPolicy: Always
      volumes:
        - name: wireguard-data
          persistentVolumeClaim:
            claimName: wireguard-longhorn
