apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:Tzbhbkzd4ij9ml9RtKrH3CM=,iv:/e1xWYvLPLx/3NiEXoQ/mPAICruWdj/4xe6tKSPNnzQ=,tag:whm9HfwM53gm5oP/+Ss7Lw==,type:str]
    client_secret: ENC[AES256_GCM,data:NunlNCwlSDmVLabv3pdkexqOBt8dAFWY6eOxWeIlSrrN4MBYqwd626taeX4EdrebP1CnBiNyYSXPTQvKR4Zp4w==,iv:338Cs44DMLpSFZwo7Mn2gFwFrgHywPeUOy2XG9MrkYM=,tag:61hq1tvR7vfnaHUGhAx8dA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcUJXcXEwM091eXdNYWlD
            c1Q0VWErUDdvMUtESGxQdG9pd0VKOUMwcUFJCmJpTnZBVzM0MXM4Qnpmai91d0tq
            TU01UE1aMjBVQjlkUU96d25HNHdDQTQKLS0tIERKVkFTY1k4WWdwLzJYeWRFV2k2
            MWNxNHlKSGdHMURzS2lJWHdWSDNzbUkKmYpuZ60Zbd8DrAdmjftOIkkA26WOibre
            nOYWFX3mZtFzj3ut7xLfgapHRqa4twH/PtrSzktae6Zrz8iP21Jz1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:17:08Z"
    mac: ENC[AES256_GCM,data:19YxcfHH98zSTYDLKpFPQYPRXvA29JtcZVI1BcZjmJTjI6Ci1Fv0RSdGVlcQmhSbfg+00q8idRp9TqNoJRmmUFTZnxcsDivFgy5l+i6E+OmbDzHa0rMJXs8s7SFTH2f0VdNetxr19Y4YzaM5bXhBxuqDyFXI7R06Ggln1UbQR2Q=,iv:nZIjePaa9lnzH17mDWbNNqOdPnWFb1AKobFM4mm1blE=,tag:kLfXOofV56XDcWlJ1SbSAQ==,type:str]
    version: 3.13.1
