apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:gJ/CmzVEfyXApDITMC9YHx3xEEv5dqT+mYb8jmnYre8GAcnUSdCjk0AMSEzAKKMauDai6x+F89Ars3VsQXfkBt39UfXQMjBjJej1zBEWruBfea1kGQc8k81YtfB7pYMzR70AzH1hVzQxNXrLYw1SaqNpaIjtuJ5T9fzWL90ZxdtuOVivEnHKVjrajRJXKvPL/QFckk9pQ3DQkiksqDsedNlC67Z1nb5QFZjg0O4Mp2RN9jZSGb/R8Q==,iv:CwieQOq4mkZgxN5kCC7zYCMwmShHdDO5WqW2xSTksDQ=,tag:QGiknybLuVZm4vr2PCK9Rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMEhoNFNHQ2VaUDBGUXdS
            MVpCOHA5c01LWHpHWExYdTVEeVFWdGkvaEMwCjBWVFVKdTc1UjJydEZaU2pXQTd3
            OXV3QW5vSGhlTGlNSW12SC9DenRDOTgKLS0tIDhKZkVhV2NlVFNYYm9ybzRNQnEx
            eXdGa0dTVkxzT1Z5a3JGYUplSmxsWncKONl3Qjvc45fgdNmzEWnleANQ+wl82wLk
            qyahja4XM8fHbscS2Bf0ojCgG1tmarXjglfklkyLKaV8bjF4VGgvow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:17:08Z"
    mac: ENC[AES256_GCM,data:d9brSAKYYXfmb+uwyBoTYqfOxO/WIcpVMLLNXvEgEkbh/5I+WkNkiq1a4zxXhEJcOsRbJWB1hhHIQ88Xu64QVVaOSHUQShTJ/kQhMHP1L1kOqY20q+5GMSwx2sHVRCFBbxrhhPI7c0FJTKMR5jGirgN+zUeAda3tz+Z7mnzoaEY=,iv:Dz4QLiVvnfjGlJeqrxvqlxNdxgg+UP0Cb7lloEoS5q8=,tag:x1R99azsOdKV6OveOna/cw==,type:str]
    version: 3.13.1
