apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-easy
  template:
    metadata:
      labels:
        app: wg-easy
    spec:
      hostNetwork: true
      containers:
        - name: wg-easy
          image: ghcr.io/wg-easy/wg-easy:15
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: PORT
              value: "8080"
            - name: HOST
              value: "0.0.0.0"
            - name: INSECURE
              value: "true"
            - name: DISABLE_IPV6
              value: "true"
            - name: INIT_PORT
              value: "51820"
          volumeMounts:
            - name: wireguard-data
              mountPath: /etc/wireguard
          ports:
            - name: web
              containerPort: 8080
              hostPort: 8080
              protocol: TCP
            - name: wireguard
              containerPort: 51820
              hostPort: 51820
              protocol: UDP
      volumes:
        - name: wireguard-data
          persistentVolumeClaim:
            claimName: wireguard-data
