apiVersion: v1
kind: Secret
metadata:
    name: wireguard-secrets
    namespace: wireguard
type: Opaque
stringData:
    INIT_USERNAME: ENC[AES256_GCM,data:aDicOvg=,iv:OiYtq4cSyi38OclRLZQSLqKgp1+mB+s0mSjW7oXtYIE=,tag:3EexVbDnkpI2NBI2o01tOw==,type:str]
    INIT_PASSWORD: ENC[AES256_GCM,data:a8Y4Y9nEdSMO9g==,iv:UvMwCS8T9AJ4JKekXqriFbzdUsVcmX83hHy2tU6nXJY=,tag:w1rVnSHleRf465MByz5T1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYmo0UVZmakR0Q3NkbmVw
            ZG5haXVUOFhGalFKSnBaUE9sRml2aWdwaGlVCnlYdUVJdzNPTlRnbE5QbStsdTRS
            YUdOSzNYM2lOQ1dWQTl2c05mUE1sQjQKLS0tIG9obk5ISzBuOVVGYlRaZmdSYmM4
            OHZKTzZKVzNiM1ptQ3YvV0RCT3B0eVUK/LFJ3HWf8RnaJwvq/MJsegIVlIWvtNQZ
            F2apaeky0G5P4+y4+Dm5/4hVoxQ94x8K1bRS8z12T1aIuTJmxQZwrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:17:08Z"
    mac: ENC[AES256_GCM,data:38a1E/kkBAoRpSAWZzMbEwa8fRuA+2O01X6hUKM/IeZhT8nemjpn2MsX8txpkLMW9kY5+nQSdIRVpZoKgmUU65VEe4EFHrmlqMkdl/jIN4IENGqIqoyEuA+HOYYseusu1cOlIjvsJJ9zuKtZW5vX1DfCgPxahAvtgiEjvX6uTeE=,iv:kqyAibygLyXKq3tZrp6WF1rHdByMpBFw7Y3+SX7jGX8=,tag:RS6LsyKugBK2EwmYHYE+Ww==,type:str]
    version: 3.13.1
