apiVersion: v1
kind: Pod
metadata:
  name: loki-data-copy
  namespace: loki
spec:
  restartPolicy: Never
  containers:
    - name: copy
      image: alpine:3.22
      command: ["/bin/sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: old-data
          mountPath: /data
        - name: new-data
          mountPath: /longhorn
  volumes:
    - name: old-data
      persistentVolumeClaim:
        claimName: loki-data
    - name: new-data
      persistentVolumeClaim:
        claimName: loki-longhorn
