apiVersion: batch/v1
kind: CronJob
metadata:
  name: duckdns-updater
  namespace: duckdns
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: duckdns
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
