apiVersion: v1
kind: Secret
metadata:
    name: duckdns-secrets
    namespace: duckdns
type: Opaque
stringData:
    DUCKDNS_DOMAIN: ENC[AES256_GCM,data:eqinZ8+z0bY=,iv:YB09BOB0NEmn7o70AosMJm/+lp2Is3RVYzo+T7UtKkE=,tag:6fLzKuuqKMjJtMAxfVk/0Q==,type:str]
    DUCKDNS_TOKEN: ENC[AES256_GCM,data:+tNtwZCI3jrGhfN2GgpRvRYKt822Rna2bpVjOLafdhb++Qdd,iv:hGu2M6SVZMmE7YzKDhyDqh+xm970buh2G0GjeeQrE7s=,tag:HMTORtMEbYpO/KbJl7a+2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T3dSWWNFMUVpRHdzWVFU
            SlRndWpFcmswSkxuWWpUdkZrT25sOHR6ZVU4CjVjTklkNEpLQTJ4ZU5sdU1IT09j
            bjF0bnJOa2dBY2dsV00xTzVYRG55VEkKLS0tIGV3RzJ6aWRsQXlzaGllemF0T3Bh
            VFNuaWVjM2RFQWxXYTNzenhXOEcyTk0KAoKq+eIEB9COOcPiClFwh7l7zq+KdIsE
            IvdirENqhPrB/R1JZ3zCo4lL0oxIfb0xWjKwRpOeMiy5+MKL7mpKkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z5mtrln9ay7u6qw59yh3ma8ym4spdglysgcnu7ehr37rpfh04egs5aczup
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T00:17:08Z"
    mac: ENC[AES256_GCM,data:Oz3jgjsNtFEoYIX1HQpzok7NkVA2hrNKxdNBLipmNSkTBIJnBufsiTtgP+eqxhfvOK00e+6iooeKZoiNJNGU93HyJGBNsX/UcbtBBt77cCSoWraVE52yrJAXbCS6+WG2Tji1ErLGnGSNBBxV2DDQ4A4VeA9qZMs84E3WvRQnpIo=,iv:IzNFT37sSOUF//o/HRouYSLN2uN9IFWw50mmxHHIeSg=,tag:8CJN886k7xm8WB7kbjrzAw==,type:str]
    version: 3.13.1
